name: movil_pucetec_api
description: A new Flutter project.
# La siguiente línea evita que el paquete se publique accidentalmente en pub.dev usando `flutter pub publish`.
# Esto es preferido para paquetes privados.
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# La siguiente define la versión y el número de compilación para tu aplicación.
# Un número de versión consta de tres números separados por puntos, como 1.2.43,
# seguido opcionalmente por un número de compilación separado por un +.
# Tanto la versión como el número de compilación pueden anularse en el flutter
# build especificando --build-name y --build-number, respectivamente.
# En Android, build-name se usa como versionName mientras que build-number se usa como versionCode.
# Lee más sobre la versión de Android en https://developer.android.com/studio/publish/versioning
# En iOS, build-name se usa como CFBundleShortVersionString mientras que build-number se usa como CFBundleVersion.
# Lee más sobre la versión de iOS en
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# En Windows, build-name se usa como las partes mayor, menor y de parche
# de las versiones de producto y de archivo, mientras que build-number se usa como el sufijo de compilación.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencias especifican otros paquetes que tu paquete necesita para funcionar.
# Para actualizar automáticamente las dependencias de tu paquete a las últimas versiones
# considera ejecutar `flutter pub upgrade --major-versions`. Alternativamente,
# las dependencias se pueden actualizar manualmente cambiando los números de versión a continuación a
# la última versión disponible en pub.dev. Para ver qué dependencias tienen versiones más recientes disponibles,
# ejecuta `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Añade las dependencias de tus paquetes aquí
  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # El paquete "flutter_lints" a continuación contiene un conjunto de lints recomendados para
  # fomentar buenas prácticas de codificación. El conjunto de lints proporcionado por el paquete está
  # activado en el archivo `analysis_options.yaml` ubicado en la raíz de tu
  # paquete. Consulta ese archivo para obtener información sobre cómo desactivar reglas de lints específicas
  # y activar otras adicionales.
  flutter_lints: ^2.0.0

# Para obtener información sobre la parte genérica de Dart de este archivo, consulta la
# siguiente página: https://dart.dev/tools/pub/pubspec

# La siguiente sección es específica de los paquetes Flutter.
flutter:
  assets:
    - img/descarga.jpeg


  # La siguiente línea asegura que la fuente de Material Icons esté
  # incluida con tu aplicación, para que puedas usar los íconos en
  # la clase de Material Icons.
  uses-material-design: true

  
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
